language: ruby
rvm:
  - 2.1.5
  - 2.2.2
  - 2.4.1
gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.1.gemfile
before_install:
  - gem install bundler
script:
  - bundle exec rspec
matrix:
  exclude:
    - rvm: 2.1.5
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_3.0.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_3.1.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3.1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.2.gemfile
